#!/bin/bash

mvn -f ./monitor-test/pom3.xml clean package

java -jar ./monitor-test/target/monitor-test-1.0-SNAPSHOT.jar

mvn -f ./ws-test/pom3.xml clean package

java -jar ./ws-test/target/ws-test3-1.0-SNAPSHOT.jar
